//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiX.Database.Squiggly.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public class cq_action
    {
        public virtual long id { get; set; }
        public virtual long id_next { get; set; }
        public virtual long id_nextfail { get; set; }
        public virtual long type { get; set; }
        public virtual int data { get; set; }
        public virtual string param { get; set; }

        public override string ToString()
        {
            var s = $"Id: {id}" + Environment.NewLine+
            $"Next -> {id_next}" +Environment.NewLine+
            $"Fail -> {id_nextfail}"+Environment.NewLine+
            $"Type -> {type}"+Environment.NewLine+
            $"Data -> {data}"+Environment.NewLine+
            $"Param: {param.Trim()}";
            return s;
        }
    }
}